processed 18 tasks

init:
A: object(0,0)

task 1 'publish'. lines 8-115:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 688560,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 117-117:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 119-123:
mutated: object(0,0)
deleted: object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 65360,  storage_rebate: 144461, non_refundable_storage_fee: 1459

task 4 'run'. lines 125-125:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 5 'run'. lines 127-127:
created: object(5,0), object(5,1)
mutated: object(0,0), object(4,0)
gas summary: computation_cost: 1000000, storage_cost: 349220,  storage_rebate: 144461, non_refundable_storage_fee: 1459

task 6 'run'. lines 129-133:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: 0xbf7b7357662e529928cc090d8657fbcc0487ba2d6b76c0eba0e44c368e7c0c22, parent_id: 0xc7931748ce6ac91e20016dae196b6d84293f63f567890c32077982878dcb634b }

task 7 'run'. lines 135-135:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 148580,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 8 'run'. lines 137-140:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 9 'run'. lines 142-142:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 148580,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 10 'run'. lines 144-144:
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 11 'run'. lines 146-149:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(0) } }

task 12 'run'. lines 151-151:
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 13 'run'. lines 153-156:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable and shared objects cannot be passed by-value.
Cannot return execution error with shared objects. Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue } at command Some(0)

task 14 'run'. lines 158-158:
created: object(14,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 15 'run'. lines 160-163:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage }, source: None, command: Some(1) } }

task 16 'run'. lines 165-165:
created: object(16,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 145920,  storage_rebate: 64706, non_refundable_storage_fee: 654

task 17 'run'. lines 167-167:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage }, source: None, command: Some(1) } }
